---
title: im kinda tipsy and thinking a lot about stuff while watching FUCKING BRAIN DEAD VIDEOS!!!!
date: 2026-05-31
---

WAHHHHHHHHHHHHHHHHHHHHH WAHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
I LOVE YOU SAYAKA CHECK THIS OUT IM SO HAPPY THAT YOU GOT A HAPPY ENDING BUT ITS SO MELANCHOLIC AND UPSETTING I WANT TO SEE MORE OF YOU AND HARU
![](https://files.catbox.moe/j3xy6v.jpg)
